apiVersion: "build.openshift.io/v1"
kind: "BuildConfig"
metadata: 
  name: "simple-pipeline"
spec:
  source:
    git: 
      uri: "https://github.com/orhanIBM/JenkinsOcp"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ./Jenkinsfile
